Repository frederic-mahe/Hardware-Target-Game-Database, pull requests merged in 2021-04, with the labels that each got.

#614 Mega Everdrive SMDB: Add Bio Hazard Battle Prototype
  EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
Labels: Genesis

#633 SNES: remove Special Chips subdirectory
  EverDrive Pack SMDBs/Super EverDrive & SD2SNES SMDB.txt
Labels: SNES

#640 MiSTer: replace Genesis/MiSTer Special Chip Games.zip with placeholder
  EverDrive Pack SMDBs/MiSTer.txt
Labels: Genesis, MiSTer

#639 MiSTer: replace Coleco zip files with placeholders
  EverDrive Pack SMDBs/MiSTer.txt
Labels: Coleco, MiSTer

#650 Genesis: move some entries from main directory to revisions
  EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
Labels: Genesis

#655 Genesis: remove redundant region roms, reorganize Betas, Color Enhancements
  EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
Labels: Genesis

#658 GBA: GSC is a subset of non-GSC
  EverDrive Pack SMDBs/EverDrive GBA SMDB.txt
Labels: translation
