Repository frederic-mahe/Hardware-Target-Game-Database, pull requests merged in 2022-04, with the labels that each got.

#775 Sms update
  EverDrive Pack SMDBs/Master EverDrive SMDB.txt
Labels: translation

#780 Mega EverDrive: placeholder entry for 32X
  EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
Labels: Genesis

#783 Wonderswan: update Klonoa translation
  EverDrive Pack SMDBs/Wonderswan SMDB.txt
Labels: translation

#788 SMS: fix Voyage - A Sorceress' Vacation hacks
  EverDrive Pack SMDBs/Master EverDrive SMDB.txt
Labels: Master System

#794 PCECD: new translations; remove Bikini Girls, J-Thunder; update Hi-Leg Fantasy
  EverDrive Pack SMDBs/PC Engine CD Redump Supplement.txt
Labels: translation, PCECD
